<script setup lang="ts">
import {onMounted,ref} from 'vue';import {useRoute,useRouter} from 'vue-router';import {useAuthStore} from '@/stores/auth';import {errorMessage} from '@/services/api';import {facebookLoginUrl} from '@/services/facebookAuth';import type {GoogleCredentialResponse} from '@/types';
const u=ref('admin'),p=ref('Admin123*'),loading=ref(false),error=ref('');const a=useAuthStore(),r=useRouter(),ruta=useRoute();
async function go(){loading.value=true;error.value='';try{const ok=await a.login(u.value.trim(),p.value);r.push(ok?(a.role==='CLIENTE'?'/mi-cuenta':'/dashboard'):'/mfa-verification')}catch(e){error.value=errorMessage(e)}finally{loading.value=false}}
async function onGoogleCredential(response:GoogleCredentialResponse){loading.value=true;error.value='';try{await a.loginWithGoogle(response.credential);r.push(a.role==='CLIENTE'?'/mi-cuenta':'/dashboard')}catch(e){error.value=errorMessage(e)}finally{loading.value=false}}
// El backend gestiona todo el intercambio OAuth (code/state/App Secret); el frontend solo redirige.
function onFacebookLogin(){window.location.assign(facebookLoginUrl())}
async function onFacebookTicket(ticket:string){loading.value=true;error.value='';try{await a.exchangeFacebookTicket(ticket);await r.replace({path:'/login',query:{}});r.push(a.role==='CLIENTE'?'/mi-cuenta':'/dashboard')}catch(e){await r.replace({path:'/login',query:{}});error.value=errorMessage(e)}finally{loading.value=false}}
onMounted(()=>{
  const ticket=ruta.query.ticket;
  if(typeof ticket==='string'&&ticket){onFacebookTicket(ticket);return}
  if(ruta.query.error){r.replace({path:'/login',query:{}});error.value='No se pudo completar el inicio de sesión con Facebook.'}
});
onMounted(()=>{let intentos=0;const timer=setInterval(()=>{const google=(window as any).google;if(google){clearInterval(timer);google.accounts.id.initialize({client_id:import.meta.env.VITE_GOOGLE_CLIENT_ID,callback:onGoogleCredential});google.accounts.id.renderButton(document.getElementById('google-btn'),{theme:'outline',size:'large',width:320,text:'continue_with'})}else if(++intentos>50){clearInterval(timer)}},100)});
</script>
<template><div class="login-page"><div class="login-art"><div class="art-copy"><span class="eyebrow">Plataforma aseguradora</span><h1>Decisiones de riesgo claras, rápidas y trazables.</h1><p>Centraliza cotizaciones, emisión, siniestros y renovaciones con una experiencia simple.</p><div class="art-metrics"><div><b>100%</b><span>Trazabilidad</span></div><div><b>Clean</b><span>Arquitectura</span></div><div><b>24/7</b><span>Disponibilidad</span></div></div></div></div><div class="login-panel"><form class="login-card" @submit.prevent="go"><div class="logo-large">A</div><h2>Bienvenido</h2><p>Ingresa para administrar Andina Seguros.</p><label>Usuario<input v-model="u" autocomplete="username" required/></label><label>Contraseña<input v-model="p" type="password" autocomplete="current-password" required/></label><div v-if="error" class="alert error">{{error}}</div><button class="primary wide" :disabled="loading">{{loading?'Ingresando…':'Iniciar sesión'}}</button><button type="button" class="fb-btn" :disabled="loading" @click="onFacebookLogin">Iniciar con Facebook</button><div class="google-divider"><span>o</span></div><div id="google-btn"></div><small>Usuario inicial sugerido: admin / Admin123*</small></form></div></div></template>
